name: build

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore .\SmtpHeaderAnalyzer.slnx
      - name: Build
        run: dotnet build .\SmtpHeaderAnalyzer.slnx -c Release -m:1 -p:UseSharedCompilation=false --no-restore
      - name: Test
        run: dotnet run --project .\tests\SmtpHeaderAnalyzer.Tests\SmtpHeaderAnalyzer.Tests.csproj -c Release --no-build
